export const ADD_TILESET = 'ADD_TILESET';
export const ADD_TILESETS = 'ADD_TILESETS';
export const SELECT_TILESET = 'SELECT_TILESET';
export const SELECT_TILE = 'SELECT_TILE';
export const CANVAS_CLICKED = 'CANVAS_CLICKED';
